// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoeuuztqgHn2Jl_vF-blQeTmIWvGDovHY',
    appId: '1:889554754586:web:edb5eb7e345a8d86a205a3',
    messagingSenderId: '889554754586',
    projectId: 'alemeno-fd677',
    authDomain: 'alemeno-fd677.firebaseapp.com',
    storageBucket: 'alemeno-fd677.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGnHx73b3SxdPiebiHVKsZi-llwdrgS70',
    appId: '1:889554754586:android:328f57872d8a1a21a205a3',
    messagingSenderId: '889554754586',
    projectId: 'alemeno-fd677',
    storageBucket: 'alemeno-fd677.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAz1_IMpcH5INZpVjVfqKC_8uPQVQ4lYDg',
    appId: '1:889554754586:ios:7476bcb0a915ec0ea205a3',
    messagingSenderId: '889554754586',
    projectId: 'alemeno-fd677',
    storageBucket: 'alemeno-fd677.appspot.com',
    iosBundleId: 'com.example.alemeno',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAz1_IMpcH5INZpVjVfqKC_8uPQVQ4lYDg',
    appId: '1:889554754586:ios:b7f18c84e0dcb985a205a3',
    messagingSenderId: '889554754586',
    projectId: 'alemeno-fd677',
    storageBucket: 'alemeno-fd677.appspot.com',
    iosBundleId: 'com.example.alemeno.RunnerTests',
  );
}
